name: pp_731
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  onboarding: ^4.0.2
  flutter_bloc: ^8.1.6
  pull_down_button: ^0.10.2
  calendar_date_picker2: ^1.1.7
  flutter_svg: ^2.0.14
  easy_date_timeline: ^1.1.3
  sqflite: ^2.3.3
  is_first_run: ^1.0.0
  shared_preferences: ^2.0.6
  custom_sliding_segmented_control: ^1.8.4
  flutter_slidable: ^3.1.1
  flutter_markdown: ^0.7.4+1
  equatable: ^2.0.5

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "Assets/Icons/Icons.webp"


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true

  assets:
    - Assets/
    - Assets/Icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: Assets/Fonts/Poppins-Regular.ttf
        - asset: Assets/Fonts/Poppins-Bold.ttf
          weight: 700

